stages:
- name: compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn clean package
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
