stages:
- name: compile
  steps:
  - runScriptConfig:
      image: fabric8/maven-builder
      shellScript: mvn clean package fabric8:build fabric8:push  -Dcheckstyle.skip=true
        -Pkubernetes -f kubernetes-hello-world-example/pom.xml
- name: deploy
  steps:
  - applyYamlConfig:
      path: kubernetes-hello-world-example/target/classes/META-INF/fabric8/kubernetes.yml
timeout: 60
notification: {}
