stages:
- name: compile
  steps:
  - runScriptConfig:
      image: registry.cn-hangzhou.aliyuncs.com/ychuang/maven:3.6.3
      shellScript: mvn clean package fabric8:build fabric8:push  -Ddocker.username=${DOCKER_USERNAME}
        -Ddocker.password=${DOCKER_PASSWORD} -Dcheckstyle.skip=true -Pkubernetes -f
        kubernetes-hello-world-example/pom.xml
    envFrom:
    - sourceName: docker
      sourceKey: DOCKER_USERNAME
      targetKey: DOCKER_USERNAME
    - sourceName: docker
      sourceKey: DOCKER_PASSWORD
      targetKey: DOCKER_PASSWORD
- name: deploy
  steps:
  - applyYamlConfig:
      path: kubernetes-hello-world-example/target/classes/META-INF/fabric8/kubernetes.yml
timeout: 60
notification: {}
