---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: f1f6b6fd90552cda611abc58de7de3631a796e30
    fabric8.io/git-branch: master
    fabric8.io/git-url: https://github.com/huangyangcong/spring-cloud-kubernetes-examples.git
    fabric8.io/scm-url: https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/kubernetes-hello-world
    fabric8.io/scm-tag: HEAD
  labels:
    app: kubernetes-hello-world
    provider: fabric8
    version: "1.0"
    group: org.springframework.cloud
  name: kubernetes-hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kubernetes-hello-world
      provider: fabric8
      group: org.springframework.cloud
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: f1f6b6fd90552cda611abc58de7de3631a796e30
        fabric8.io/git-branch: master
        fabric8.io/scm-tag: HEAD
        fabric8.io/git-url: https://github.com/huangyangcong/spring-cloud-kubernetes-examples.git
        fabric8.io/scm-url: https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/kubernetes-hello-world
      labels:
        app: kubernetes-hello-world
        provider: fabric8
        version: "1.0"
        group: org.springframework.cloud
    spec:
      serviceAccountName: kubernetes-example
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: cloud/kubernetes-hello-world:1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: spring-boot
          ports:
            - containerPort: 8081
              name: sunproxyadmin
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
