kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-example
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
